# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  name: MP.Windows

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

stages:
  - stage: BuildInDebugMode
  
    variables:
    - name: buildConfiguration
      value: 'Debug'
    - name: Major
      value: 1.0.$(Rev:.rrrr)

    jobs:
    - job: buildAndTest
      timeoutInMinutes: 150
      steps:
      - checkout: self
        clean: true
      
      - template: /.pipelineTemplates/BuildAndTest.yml
  
      - template: /.pipelineTemplates/NuGetPackagePublish.yml
  
  - stage: BuildInReleaseMode
  
    variables:
    - name: buildConfiguration
      value: 'Release'

    jobs:
    - job: buildAndTest
      timeoutInMinutes: 150
      steps:
      - checkout: self
        clean: true
      
      - template: /.pipelineTemplates/BuildAndTest.yml
    
